# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 04:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteActividad',
            fields=[
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReporte', models.DateField()),
                ('recomendadosObtenidos', models.IntegerField()),
                ('recomendadosContactados', models.IntegerField()),
                ('llamadasRealizadas', models.IntegerField()),
                ('citasObtenidas', models.IntegerField()),
                ('citasTotales', models.IntegerField()),
                ('citasNuevas', models.IntegerField()),
                ('entrevistasInicialesPlaneadas', models.IntegerField()),
                ('entrevistasInicialesRealizadas', models.IntegerField()),
                ('entrevistasCierrePlaneadas', models.IntegerField()),
                ('entrevistasCierreRealizadas', models.IntegerField()),
                ('solicitudesSucritas', models.IntegerField()),
                ('idAsesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
