# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='idAsesor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
