# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asesor', '0002_auto_20171028_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesor',
            name='idAsesor',
        ),
        migrations.AlterField(
            model_name='reporteactividad',
            name='idAsesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Asesor',
        ),
    ]
