# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
