# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idCita',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
