# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20171123_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idAsesorCliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.AsesorCliente'),
        ),
    ]
