# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20171123_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idEstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.CatEstatuscita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='idTipoCita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.CatTipocita'),
        ),
    ]
