# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('productos', '0002_auto_20180120_2107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanesConcretados',
            fields=[
                ('idPlan', models.AutoField(primary_key=True, serialize=False)),
                ('fechaContratacion', models.DateField()),
                ('numeroPoliza', models.CharField(max_length=10)),
                ('primaNetaAnual', models.FloatField()),
                ('plazoAnos', models.IntegerField()),
                ('valorPlan', models.FloatField()),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('idAsesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Persona')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Servicio')),
            ],
        ),
    ]
