# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.6 on 2017-11-04 21:12
=======
# Generated by Django 1.11.5 on 2017-11-04 21:12
>>>>>>> 962c8a0b8b5743f55979243e4cfc6000022daafe
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('login', '0001_initial'),
        ('productos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
        ('productos', '0001_initial'),
>>>>>>> 962c8a0b8b5743f55979243e4cfc6000022daafe
    ]

    operations = [
        migrations.CreateModel(
            name='PlanesConcretados',
            fields=[
                ('idPlan', models.AutoField(primary_key=True, serialize=False)),
                ('fechaContratacion', models.TimeField()),
                ('numeroPoliza', models.CharField(max_length=10)),
                ('primaNetaAnual', models.FloatField()),
                ('plazoAnos', models.IntegerField()),
                ('valorPlan', models.FloatField()),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('idAsesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Persona')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Servicio')),
            ],
        ),
    ]
