# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estadoCivil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.EstadoCivil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='idRol',
            field=models.ManyToManyField(blank=True, null=True, to='login.Roles'),
        ),
    ]
