# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171003_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='idtipodireccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.CatTipodireccion'),
        ),
    ]
