# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170909_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='idRol',
            field=models.ManyToManyField(to='login.Roles'),
        ),
    ]
