# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20171008_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='email',
        ),
    ]
