# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('asesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsesorCliente',
            fields=[
                ('idAsesorCliente', models.AutoField(primary_key=True, serialize=False)),
                ('fechaActualizacion', models.DateField()),
                ('ocupacion', models.CharField(blank=True, max_length=150, null=True)),
                ('dependientes', models.CharField(blank=True, max_length=150, null=True)),
                ('ingresos', models.FloatField(blank=True, null=True)),
                ('idAsesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asesor.Asesor')),
                ('idCliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='CatClienteProspecto',
            fields=[
                ('idClienteProspecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('idEstatus', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrigenRecomendacion',
            fields=[
                ('idOrigen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='asesorcliente',
            name='idClienteProspecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.CatClienteProspecto'),
        ),
        migrations.AddField(
            model_name='asesorcliente',
            name='idEstatus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.Estatus'),
        ),
        migrations.AddField(
            model_name='asesorcliente',
            name='idOrigen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente.OrigenRecomendacion'),
        ),
    ]
