# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorcliente',
            name='fechaActual',
            field=models.DateField(blank=True, null=True),
        ),
    ]
