# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorcliente',
            name='Estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Estatus'),
        ),
        migrations.AlterField(
            model_name='asesorcliente',
            name='Origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.OrigenRecomendacion'),
        ),
    ]
