# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('cliente', '0002_auto_20171022_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendadocliente',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Persona'),
        ),
    ]
