# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20171125_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asesorcliente',
            old_name='fechaActual',
            new_name='citaActual',
        ),
    ]
