# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20171126_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesorcliente',
            name='citaActual',
        ),
        migrations.AddField(
            model_name='asesorcliente',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
