# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20180112_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorcliente',
            name='estatusCita',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
