# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_asesorcliente_estatuscita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorcliente',
            name='estatusCita',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
