# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20180112_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendadocliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='recomendadocliente',
            name='vivienda',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
