# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_auto_20180112_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendadocliente',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
