# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion1',
            name='blindajeFinancieroidbl',
        ),
        migrations.RemoveField(
            model_name='sesion1',
            name='idAsesorCliente',
        ),
        migrations.RemoveField(
            model_name='sesion1',
            name='idCapitalizacion',
        ),
        migrations.RemoveField(
            model_name='sesion1',
            name='libertadFinancieraiDlf',
        ),
        migrations.DeleteModel(
            name='Blindajefinanciero',
        ),
        migrations.DeleteModel(
            name='Capitalizacion',
        ),
        migrations.DeleteModel(
            name='Libertadfinanciera',
        ),
        migrations.DeleteModel(
            name='Sesion1',
        ),
    ]
