# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='nombre',
            new_name='nombrePlan',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='idDepartamento',
            field=models.ForeignKey(db_column='unique_together', on_delete=django.db.models.deletion.CASCADE, to='productos.Departamento'),
        ),
    ]
