spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vive_tu_futuro
    username: vive
    password: vive
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect 